export interface Chapter {
  id: string;
  number: number;
  title: string;
  category: "Pure" | "Statistics" | "Mechanics";
  year: 1 | 2;
}

export const aLevelMathsChapters: Chapter[] = [
  // Pure Year 1
  { id: "p1_c1", number: 1, title: "Algebraic Expressions", category: "Pure", year: 1 },
  { id: "p1_c2", number: 2, title: "Quadratics", category: "Pure", year: 1 },
  { id: "p1_c3", number: 3, title: "Equations and Inequalities", category: "Pure", year: 1 },
  { id: "p1_c4", number: 4, title: "Graphs and Transformations", category: "Pure", year: 1 },
  { id: "p1_c5", number: 5, title: "Straight Line Graphs", category: "Pure", year: 1 },
  { id: "p1_c6", number: 6, title: "Circles", category: "Pure", year: 1 },
  { id: "p1_c7", number: 7, title: "Algebraic Methods", category: "Pure", year: 1 },
  { id: "p1_c8", number: 8, title: "The Binomial Expansion", category: "Pure", year: 1 },
  { id: "p1_c9", number: 9, title: "Trigonometric Ratios", category: "Pure", year: 1 },
  { id: "p1_c10", number: 10, title: "Trigonometric Identities and Equations", category: "Pure", year: 1 },
  { id: "p1_c11", number: 11, title: "Vectors", category: "Pure", year: 1 },
  { id: "p1_c12", number: 12, title: "Differentiation", category: "Pure", year: 1 },
  { id: "p1_c13", number: 13, title: "Integration", category: "Pure", year: 1 },
  { id: "p1_c14", number: 14, title: "Exponentials and Logarithms", category: "Pure", year: 1 },

  // Pure Year 2
  { id: "p2_c1", number: 1, title: "Algebraic Methods", category: "Pure", year: 2 },
  { id: "p2_c2", number: 2, title: "Functions and Graphs", category: "Pure", year: 2 },
  { id: "p2_c3", number: 3, title: "Sequences and Series", category: "Pure", year: 2 },
  { id: "p2_c4", number: 4, title: "Binomial Expansion", category: "Pure", year: 2 },
  { id: "p2_c5", number: 5, title: "Radians", category: "Pure", year: 2 },
  { id: "p2_c6", number: 6, title: "Trigonometric Functions", category: "Pure", year: 2 },
  { id: "p2_c7", number: 7, title: "Trigonometry and Modelling", category: "Pure", year: 2 },
  { id: "p2_c8", number: 8, title: "Parametric Equations", category: "Pure", year: 2 },
  { id: "p2_c9", number: 9, title: "Differentiation", category: "Pure", year: 2 },
  { id: "p2_c10", number: 10, title: "Numerical Methods", category: "Pure", year: 2 },
  { id: "p2_c11", number: 11, title: "Integration", category: "Pure", year: 2 },
  { id: "p2_c12", number: 12, title: "Vectors", category: "Pure", year: 2 },

  // Statistics
  { id: "s1_c1", number: 1, title: "Data Collection", category: "Statistics", year: 1 },
  { id: "s1_c2", number: 2, title: "Measures of Location and Spread", category: "Statistics", year: 1 },
  { id: "s1_c3", number: 3, title: "Representations of Data", category: "Statistics", year: 1 },
  { id: "s1_c4", number: 4, title: "Correlation", category: "Statistics", year: 1 },
  { id: "s1_c5", number: 5, title: "Probability", category: "Statistics", year: 1 },
  { id: "s1_c6", number: 6, title: "Statistical Distributions", category: "Statistics", year: 1 },
  { id: "s1_c7", number: 7, title: "Hypothesis Testing", category: "Statistics", year: 1 },

  // Mechanics
  { id: "m1_c1", number: 1, title: "Modelling in Mechanics", category: "Mechanics", year: 1 },
  { id: "m1_c2", number: 2, title: "Constant Acceleration", category: "Mechanics", year: 1 },
  { id: "m1_c3", number: 3, title: "Forces and Motion", category: "Mechanics", year: 1 },
  { id: "m1_c4", number: 4, title: "Variable Acceleration", category: "Mechanics", year: 1 },
];

/**
 * Mapping from Topic name to Chapter
 */
export const topicToChapter: Record<string, string> = {
  "Algebra": "p1_c1",
  "Functions": "p2_c2",
  "Trigonometry": "p1_c9",
  "Calculus": "p1_c12",
  "Coordinate Geometry": "p1_c5",
  "Sequences and Series": "p2_c3",
  "Vectors": "p1_c11",
  "Data Collection": "s1_c1",
  "Probability": "s1_c5",
  "Statistics": "s1_c6",
  "Mechanics": "m1_c3",
  "Exponentials and Logarithms": "p1_c14",
  // Specific User Topics
  "Small Angle Approximations": "p2_c7",
  "Differentiation - Stationary Points": "p1_c12",
  "Radians": "p2_c5",
  "Iteration": "p2_c10",
  "Differentiation - Quotient Rule": "p2_c9",
  "Circles": "p1_c6",
  "Integration - Standard": "p1_c13",
  "Modelling with Trigonometry": "p2_c7",
  "Differentiation - Implicit": "p2_c9",
  "Modelling with Differential Equations": "p2_c11",
  "Binomial Expansion (A2)": "p2_c4",
  "Geometric Sequences": "p2_c3",
  "Integration - By Parts": "p2_c11",
  "Parametric Equations": "p2_c8",
  "Vectors (A2)": "p2_c12",
  "Proofs | Modulus": "p2_c2",
  "Sequences": "p2_c3",
  "Numerical Methods - Newton Raphson": "p2_c10",
  "Quadratics - Hidden Quadratics": "p1_c2",
  "Solving Trigonometric Equations": "p1_c10",
  "Modelling with Quadratics": "p1_c2",
  "Differentiation - First Principles (sin and cos)": "p2_c9",
  "Partial Fractions - Improper": "p2_c1",
  "Trigonometry (A2)": "p2_c7",
  "Differentiation (A2)": "p2_c9",
  "Factor Theorem": "p1_c7",
  "Graph Transformations": "p1_c4",
  "Modelling with Exponentials": "p1_c14",
  "Integration (AS)": "p1_c13",
  "Logarithms": "p1_c14",
  "Proofs (AS)": "p1_c7",
  "Differentiation - Product Rule": "p2_c9",
  "Integration - Partial Fractions": "p2_c11",
  "Indices": "p1_c1",
  "Integration - Trapezium Rule": "p2_c10",
  "Integration - Limit of a Sum": "p2_c11",
  "Modelling with Straight Lines": "p1_c5",
  "Modelling with Logarithms": "p1_c14",
  "Differentiation (AS)": "p1_c12",
  "Integration - Substitution": "p2_c11",
  "Arithmetic Sequences": "p2_c3",
  "Modelling with R Conversions": "p2_c7",
  "Inequalities on Graphs": "p1_c3",
  "Connected Rates of Change": "p2_c9",
  "Proofs - Contradiction": "p2_c1",
  "Binomial Expansion (AS)": "p1_c8",
  "Trigonometry (AS)": "p1_c9",
  "Modulus": "p2_c2",
  "Integration - Chain Rule": "p2_c11",
  "Completing the Square": "p1_c2",
  "Numerical Methods": "p2_c10",
  "Differentiation - Sketching Frist Derivative": "p1_c12",
  "Trigonometry - Compound Angles": "p2_c7",
  "Integration - Parametrics": "p2_c11",
  "Exponentials": "p1_c14",
  "Differentiation - First Principles": "p1_c12",
  "Partial Fractions Functions": "p2_c1",
  "Differentiation - Parametrics": "p2_c9",
  "Differentiation - Concavity": "p2_c9",
  "Vectors (AS)": "p1_c11",
};
